### ISSUE TITLE
Move documentation to a docs directory

### ISSUE THREAD

**Issue by pxgamer** [pxgamer/arionum-php#14]
## Detailed description

Currently all documentation is in the [`README`](//github.com/pxgamer/arionum-php/blob/master/README.md) file. It would be good to move it to a `docs` directory.

## Possible implementation

```bash
docs/
  examples/        # A directory containing simple usage examples
  README.md        # A list of available documentation pages
  general-usage.md # A list of available commands on the `Arionum` class
  transactions.md  # A list of transaction methods
```

This is open to changes though. :+1:

**Comment by LiamBailey** [comment]
Is this still open?
